sudo: required
services:
  - docker

before_install:
  - docker build -t prabhav1996/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true prabhav1996/docker-react npm run test

language: generic 
