sudo: required
services:
  - docker

before_install:
  - docker build -t prabhav1996/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true prabhav1996/docker-react npm run test

language: generic 

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-972304023365"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY