FROM node:alpine

WORKDIR /app

COPY package.json .

RUN npm install -g npm@7.20.0
#RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

USER node

CMD ["npm", "run", "start"]